/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_parcial_2;

/**
 *
 * @author Ramón
 */
public class Encriptar_DesencriptarForm extends javax.swing.JFrame {

    /**
     * Creates new form Encriptar_DesencriptarForm
     */
    
    String encryptText;
    String desencryptText;
    EncriptarYDesencriptar encriptDesencript;
    
    public Encriptar_DesencriptarForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textEncryptTxa = new javax.swing.JTextArea();
        planeTextTxt = new javax.swing.JTextField();
        planeTextLbl = new javax.swing.JLabel();
        textEncryptLbl = new javax.swing.JLabel();
        encryptTextBtn = new javax.swing.JButton();
        planeTextLbl1 = new javax.swing.JLabel();
        planeText2Txt = new javax.swing.JTextField();
        textEncryptLbl1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textEncrypt2Txa = new javax.swing.JTextArea();
        desencryptTextBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Encriptacion y desencriptacion de texto");

        textEncryptTxa.setEditable(false);
        textEncryptTxa.setBackground(new java.awt.Color(204, 204, 204));
        textEncryptTxa.setColumns(20);
        textEncryptTxa.setForeground(new java.awt.Color(0, 0, 0));
        textEncryptTxa.setLineWrap(true);
        textEncryptTxa.setRows(5);
        jScrollPane1.setViewportView(textEncryptTxa);

        planeTextTxt.setBackground(new java.awt.Color(204, 204, 204));
        planeTextTxt.setForeground(new java.awt.Color(0, 0, 0));

        planeTextLbl.setBackground(new java.awt.Color(255, 255, 255));
        planeTextLbl.setForeground(new java.awt.Color(0, 0, 0));
        planeTextLbl.setText("Texto Plano");

        textEncryptLbl.setBackground(new java.awt.Color(255, 255, 255));
        textEncryptLbl.setForeground(new java.awt.Color(0, 0, 0));
        textEncryptLbl.setText("Texto Encriptado");

        encryptTextBtn.setBackground(new java.awt.Color(255, 153, 51));
        encryptTextBtn.setForeground(new java.awt.Color(0, 0, 0));
        encryptTextBtn.setText("Encriptar Texto");
        encryptTextBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        encryptTextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encryptTextBtnActionPerformed(evt);
            }
        });

        planeTextLbl1.setBackground(new java.awt.Color(255, 255, 255));
        planeTextLbl1.setForeground(new java.awt.Color(0, 0, 0));
        planeTextLbl1.setText("Texto Desencriptado");

        planeText2Txt.setEditable(false);
        planeText2Txt.setBackground(new java.awt.Color(204, 204, 204));
        planeText2Txt.setForeground(new java.awt.Color(0, 0, 0));

        textEncryptLbl1.setBackground(new java.awt.Color(255, 255, 255));
        textEncryptLbl1.setForeground(new java.awt.Color(0, 0, 0));
        textEncryptLbl1.setText("Texto Encriptado");

        textEncrypt2Txa.setBackground(new java.awt.Color(204, 204, 204));
        textEncrypt2Txa.setColumns(20);
        textEncrypt2Txa.setForeground(new java.awt.Color(0, 0, 0));
        textEncrypt2Txa.setLineWrap(true);
        textEncrypt2Txa.setRows(5);
        jScrollPane2.setViewportView(textEncrypt2Txa);

        desencryptTextBtn.setBackground(new java.awt.Color(255, 153, 51));
        desencryptTextBtn.setForeground(new java.awt.Color(0, 0, 0));
        desencryptTextBtn.setText("Desencriptar Texto");
        desencryptTextBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        desencryptTextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desencryptTextBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(planeTextTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(planeTextLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(82, 82, 82))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jScrollPane1)
                        .addGap(13, 13, 13))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(textEncryptLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(encryptTextBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(53, 53, 53)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(planeText2Txt))
                        .addGap(119, 119, 119))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(textEncryptLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(173, 173, 173))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(desencryptTextBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                .addGap(171, 171, 171))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(planeTextLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(176, 176, 176))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(257, 257, 257)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(251, 251, 251))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(planeTextLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(planeTextTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(textEncryptLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(encryptTextBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(planeTextLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(planeText2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(textEncryptLbl1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(desencryptTextBtn)))
                .addGap(130, 130, 130))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void encryptTextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encryptTextBtnActionPerformed
        // TODO add your handling code here:
        encriptDesencript = new EncriptarYDesencriptar();
        desencryptText = planeTextTxt.getText();
        encryptText = encriptDesencript.encryptMethod(desencryptText);
        textEncryptTxa.setText(encryptText);
    }//GEN-LAST:event_encryptTextBtnActionPerformed

    private void desencryptTextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desencryptTextBtnActionPerformed
        // TODO add your handling code here:
        encriptDesencript = new EncriptarYDesencriptar();
        encryptText = textEncrypt2Txa.getText();
        desencryptText = encriptDesencript.desencryptMethod(encryptText);
        planeText2Txt.setText(desencryptText);
    }//GEN-LAST:event_desencryptTextBtnActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton desencryptTextBtn;
    private javax.swing.JButton encryptTextBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField planeText2Txt;
    private javax.swing.JLabel planeTextLbl;
    private javax.swing.JLabel planeTextLbl1;
    private javax.swing.JTextField planeTextTxt;
    private javax.swing.JTextArea textEncrypt2Txa;
    private javax.swing.JLabel textEncryptLbl;
    private javax.swing.JLabel textEncryptLbl1;
    private javax.swing.JTextArea textEncryptTxa;
    // End of variables declaration//GEN-END:variables
}
